<a href="https://colab.research.google.com/github/muhammad-umar-9/Python-Codes/blob/main/Arrays_and_vector_with_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [37]:
list_a = [ 2 , 4 ,8]
list_b = [ 5 , 6 , 7]
# we cannot multiply list elements by using just list-a * list-b
#list_a * list_b

In [2]:
list_c =[]
for i in list_a:
  for j in list_b:
    list_c.append(i*j)
    print(list_c)

[10]
[10, 12]
[10, 12, 14]
[10, 12, 14, 20]
[10, 12, 14, 20, 24]
[10, 12, 14, 20, 24, 28]
[10, 12, 14, 20, 24, 28, 40]
[10, 12, 14, 20, 24, 28, 40, 48]
[10, 12, 14, 20, 24, 28, 40, 48, 56]


In [3]:
# To perform element-wise multiplication between two lists, you could
# use a for loop.
list_c = []
for i in range(len(list_a)):
    list_c.append(list_a[i] * list_b[i])

list_c

[10, 24, 56]

In [4]:
import numpy as np
array_a = np.array(list_a)
array_b = np.array(list_b)

array_a * array_b

array([10, 24, 56])

In [8]:
# 1-D array
#one-dimensional array is similar to a list.
import numpy as np
array_1d = np.array([1, 2, 3])
array_1d

array([1, 2, 3])

In [7]:
# 2-D array
#two-dimensional array is similar to a table.
import numpy as np
array_2d = np.array([[1 , 2 ,3], [2 , 5 ,6]])
array_2d

array([[1, 2, 3],
       [2, 5, 6]])

In [9]:
# 3-D array
#three-dimensional array is similar to two tables.
import numpy as np
array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
array_3d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [1]:
#This creates an array of a designated shape that is pre-filled with zeros:
import numpy as np
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [2]:
import numpy as np
np.zeros((2, 3, 4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [3]:
#This creates an array of a designated shape that is pre-filled with ones:
import numpy as np
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [4]:
#this creates an array of a designated shape that is pre-filled with a specified value:
import numpy as np
np.full((3, 3), 5)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [5]:
#                                                         ARRAY METHODS
#This returns a copy of the array collapsed into one dimension.
import numpy as np
array_1d = np.array([1, 2, 3])
array_1d.flatten()

array([1, 2, 3])

In [6]:
array_2d = np.array([(1, 2, 3), (4, 5, 6)])
print(array_2d)
print()
array_2d.flatten()

[[1 2 3]
 [4 5 6]]



array([1, 2, 3, 4, 5, 6])

In [9]:
#This gives a new shape to an array without changing its data.
import numpy as np
array_1d = np.array([1, 2, 3])
array_1d.reshape((3, 1))

array([[1],
       [2],
       [3]])

In [10]:
array_1d.reshape((1, 3))

array([[1, 2, 3]])

In [11]:
array_2d = np.array([(1, 2, 3), (4, 5, 6)])
print(array_2d)
print()
array_2d.reshape(3, 2)

[[1 2 3]
 [4 5 6]]



array([[1, 2],
       [3, 4],
       [5, 6]])

In [12]:
array_2d.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
#This converts an array to a list object. Multidimensional arrays are converted to nested lists.
import numpy as np
array_1d = np.array([1, 2, 3])
array_1d.tolist()

[1, 2, 3]

In [14]:
array_2d = np.array([(1, 2, 3), (4, 5, 6)])
print(array_2d)
print()
array_2d.tolist()

[[1 2 3]
 [4 5 6]]



[[1, 2, 3], [4, 5, 6]]

In [21]:
#                                                   Mathematical functions
#returns the maximum value in the array or along a specified axis.
# returns the mean of all the values in the array or along a specified axis.
# returns the minimum value in the array or along a specified axis.
# returns the standard deviation of all the values in the array or along a specified axis.
# returns the sum of all the values in the array or along a specified axis.
# returns the product of all the values in the array or along a specified axis.
# returns the cumulative sum of all the values in the array or along a specified axis.
# returns the cumulative product of all the values in the array or along a specified axis.
# returns the index of the maximum value in the array or along a specified axis.
# returns the index of the minimum value in the array or along a specified axis.
a = np.array([(1, 2, 3), (4, 5, 6)])
print(a)

print(a.max())
print(a.mean())
print(a.min())
print(a.std())
print(a.sum())
print(a.prod())
print(a.cumsum())
print(a.cumprod())
print(a.argmax())
print(a.argmin())

[[1 2 3]
 [4 5 6]]
6
3.5
1
1.707825127659933
21
720
[ 1  3  6 10 15 21]
[  1   2   6  24 120 720]
5
0


In [22]:
#                                                                     Array attributes
# returns a tuple of the array’s dimensions.
#returns the data type of the array’s contents.
#returns the total number of elements in the array.
#returns the array transposed (rows become columns, columns become rows).


array_2d = np.array([(1, 2, 3), (4, 5, 6)])
print(array_2d)
print()

print(array_2d.shape)
print(array_2d.dtype)
print(array_2d.size)
print(array_2d.T)

[[1 2 3]
 [4 5 6]]

(2, 3)
int64
6
[[1 4]
 [2 5]
 [3 6]]


In [30]:
#                                                             Indexing and slicing
a = np.array([(1, 2, 3), (4, 5, 6)])

print(a[0])
print("   ")
print(a[1])
print("   ")
print(a[0, 1])
print(a[1, 2])

print(a[0][1])
print("   ")
print(a[1][2])

[1 2 3]
   
[4 5 6]
   
2
6
2
   
6


In [32]:
#Slicing may also be used to access subarrays of a NumPy array:
a = np.array([(1, 2, 3), (4, 5, 6)])


a[:, 1:]

array([[2, 3],
       [5, 6]])

In [33]:
#                                                           Array operations
#addition and subtraction
#multiplication and division

a = np.array([(1, 2, 3), (4, 5, 6)])
b = np.array([[1, 2, 3], [1, 2, 3]])
print('a:')
print(a)
print()
print('b:')
print(b)
print()
print('a + b:')
print(a + b)
print()
print('a * b:')
print(a * b)

a:
[[1 2 3]
 [4 5 6]]

b:
[[1 2 3]
 [1 2 3]]

a + b:
[[2 4 6]
 [5 7 9]]

a * b:
[[ 1  4  9]
 [ 4 10 18]]


In [34]:
#                                                       Mutability


a = np.array([(1, 2), (3, 4)])
print(a)
print()

a[1][1] = 100
a

[[1 2]
 [3 4]]



array([[  1,   2],
       [  3, 100]])

In [35]:
a = np.array([1, 2, 3])
print(a)
print()

a[3] = 100
a

[1 2 3]



IndexError: index 3 is out of bounds for axis 0 with size 3